spring:
  application:
    name: nestalk
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  profiles:
    active: local
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:nestalk;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
server:
  port: 8080
jwt:
  token:
    header: x-access-token
    issuer: nestalk
    secret: [ SECRET KEY ]
    expirationTime: 0

kafka:
  consumer:
    bootstrap-servers: localhost:9092
    group-id: kafka-module
    auto-offset-reset: earliest
    key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: com.doongji.nestalk.entity
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer